name: The Travel Fairy
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a1915'
    - '#56b6c4'
    - '#b95190'
    - '#f5ea2e'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
